FIX: workaround lock rotation regression on "b2g-18.0.2013-05-22"
gaia system app nodePrincipal.appStatus reported as "app not installed"
(nodePrincipal.appStatus == APP_STATUS_NOT_INSTALLED)

Console Messages:

     Error: deny mozLockOrientation:"
     Source File: jar:file:///.../b2g-prosthesis@mozilla.org.xpi!/components/SimulatorScreen.js
     Line: 210